export const languageOptions = [
  ["en", "English"],
  ["hi", "हिन्दी"],
  ["bn", "বাংলা"],
  ["mr", "मराठी"],
  ["te", "తెలుగు"],
  ["ta", "தமிழ்"],
  ["gu", "ગુજરાતી"],
  ["ur", "اردو"],
  ["kn", "ಕನ್ನಡ"]
];

const localeKey = "directagri-locale";

export function getLocale() {
  if (typeof window === "undefined") return "en";
  const saved = window.localStorage.getItem(localeKey);
  return languageOptions.some(([code]) => code === saved) ? saved : "en";
}

export function setLocale(locale) {
  if (typeof window !== "undefined" && languageOptions.some(([code]) => code === locale)) {
    window.localStorage.setItem(localeKey, locale);
  }
}

export function applyLocale(locale) {
  if (typeof document !== "undefined") {
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === "ur" ? "rtl" : "ltr";
  }
}

export const authTranslations = {
  en: { already: "Already have an account? Log in", newHere: "New here? Sign up", eyebrow: "A fairer route to market", heroTitle: "Keep more of what you grow.", heroText: "One calm workspace for crop listings, buyers, transport, storage and transparent settlement.", access: "DirectAgri access", create: "Create your account", welcome: "Welcome back", chooseRole: "Choose the role that matches your place in the ecosystem.", signInText: "Sign in with your DirectAgri account.", name: "Full name", email: "Email", password: "Password", role: "Your role", forgot: "Forgot password?", submitCreate: "Create account", submitLogin: "Log in", opening: "Opening workspace...", demo: "Demo login · password demo1234", storage: "Storage partner", recoveryTitle: "Reset your password", recoveryText: "Enter your email and reset code.", sendCode: "Send reset code", sending: "Sending code...", resetCode: "Reset code", newPassword: "New password", confirmPassword: "Confirm password", repeatPassword: "Repeat new password", updatePassword: "Update password", updating: "Updating password...", backLogin: "Back to log in", createAccount: "Create an account", mismatch: "New password and confirm password do not match." },
  hi: { already: "पहले से खाता है? लॉग इन करें", newHere: "नए हैं? साइन अप करें", eyebrow: "खेत से बाजार तक बेहतर रास्ता", heroTitle: "अपनी उपज का अधिक मूल्य रखें।", heroText: "फसल सूची, खरीदार, परिवहन, भंडारण और पारदर्शी भुगतान का एक कार्यक्षेत्र।", access: "DirectAgri पहुंच", create: "खाता बनाएं", welcome: "वापसी पर स्वागत है", chooseRole: "अपने काम से मेल खाने वाली भूमिका चुनें।", signInText: "अपने DirectAgri खाते से लॉग इन करें।", name: "पूरा नाम", email: "ईमेल", password: "पासवर्ड", role: "आपकी भूमिका", forgot: "पासवर्ड भूल गए?", submitCreate: "खाता बनाएं", submitLogin: "लॉग इन", opening: "कार्यस्थल खुल रहा है...", demo: "डेमो लॉगिन · पासवर्ड demo1234", storage: "भंडारण भागीदार", recoveryTitle: "पासवर्ड रीसेट करें", recoveryText: "अपना ईमेल और रीसेट कोड डालें।", sendCode: "रीसेट कोड भेजें", sending: "कोड भेज रहे हैं...", resetCode: "रीसेट कोड", newPassword: "नया पासवर्ड", confirmPassword: "पासवर्ड की पुष्टि", repeatPassword: "नया पासवर्ड दोहराएं", updatePassword: "पासवर्ड अपडेट करें", updating: "पासवर्ड अपडेट हो रहा है...", backLogin: "लॉग इन पर वापस जाएं", createAccount: "खाता बनाएं", mismatch: "नया पासवर्ड और पुष्टि पासवर्ड समान नहीं हैं।" },
  mr: { already: "खाते आहे? लॉग इन करा", newHere: "नवीन आहात? साइन अप करा", eyebrow: "शेतातून बाजारापर्यंत योग्य मार्ग", heroTitle: "तुमच्या पिकाचे अधिक मूल्य ठेवा.", heroText: "पीक नोंद, खरेदीदार, वाहतूक, साठवण आणि पारदर्शक पेमेंटसाठी एक कार्यक्षेत्र.", access: "DirectAgri प्रवेश", create: "खाते तयार करा", welcome: "पुन्हा स्वागत आहे", chooseRole: "तुमच्या कामाशी जुळणारी भूमिका निवडा.", signInText: "तुमच्या DirectAgri खात्याने लॉग इन करा.", name: "पूर्ण नाव", email: "ईमेल", password: "पासवर्ड", role: "तुमची भूमिका", forgot: "पासवर्ड विसरलात?", submitCreate: "खाते तयार करा", submitLogin: "लॉग इन", opening: "कार्यस्थळ उघडत आहे...", demo: "डेमो लॉगिन · पासवर्ड demo1234", storage: "साठवण भागीदार" },
  bn: { already: "অ্যাকাউন্ট আছে? লগ ইন করুন", newHere: "নতুন? সাইন আপ করুন", eyebrow: "খামার থেকে বাজারে ন্যায্য পথ", heroTitle: "আপনার উৎপাদনের বেশি মূল্য রাখুন।", heroText: "ফসলের তালিকা, ক্রেতা, পরিবহন, সংরক্ষণ ও স্বচ্ছ নিষ্পত্তির এক কর্মক্ষেত্র।", access: "DirectAgri প্রবেশ", create: "অ্যাকাউন্ট তৈরি করুন", welcome: "আবার স্বাগতম", chooseRole: "আপনার কাজের সঙ্গে মেলে এমন ভূমিকা বেছে নিন।", signInText: "আপনার DirectAgri অ্যাকাউন্ট দিয়ে লগ ইন করুন।", name: "পুরো নাম", email: "ইমেল", password: "পাসওয়ার্ড", role: "আপনার ভূমিকা", forgot: "পাসওয়ার্ড ভুলে গেছেন?", submitCreate: "অ্যাকাউন্ট তৈরি করুন", submitLogin: "লগ ইন", opening: "কর্মক্ষেত্র খোলা হচ্ছে...", demo: "ডেমো লগইন · পাসওয়ার্ড demo1234", storage: "সংরক্ষণ অংশীদার" },
  te: { already: "ఖాతా ఉందా? లాగిన్ చేయండి", newHere: "కొత్తవారా? సైన్ అప్ చేయండి", eyebrow: "పొలం నుండి మార్కెట్‌కు న్యాయమైన మార్గం", heroTitle: "మీ పంట విలువలో ఎక్కువ భాగం ఉంచుకోండి.", heroText: "పంట జాబితాలు, కొనుగోలుదారులు, రవాణా, నిల్వ మరియు పారదర్శక చెల్లింపుల కోసం ఒక పని స్థలం.", access: "DirectAgri ప్రవేశం", create: "ఖాతా సృష్టించండి", welcome: "తిరిగి స్వాగతం", chooseRole: "మీ పనికి సరిపోయే పాత్రను ఎంచుకోండి.", signInText: "మీ DirectAgri ఖాతాతో లాగిన్ చేయండి.", name: "పూర్తి పేరు", email: "ఈమెయిల్", password: "పాస్‌వర్డ్", role: "మీ పాత్ర", forgot: "పాస్‌వర్డ్ మర్చిపోయారా?", submitCreate: "ఖాతా సృష్టించండి", submitLogin: "లాగిన్", opening: "వర్క్‌స్పేస్ తెరుచుకుంటోంది...", demo: "డెమో లాగిన్ · పాస్‌వర్డ్ demo1234", storage: "నిల్వ భాగస్వామి" },
  ta: { already: "கணக்கு உள்ளதா? உள்நுழைக", newHere: "புதியவரா? பதிவு செய்க", eyebrow: "பண்ணையிலிருந்து சந்தைக்கு நியாயமான பாதை", heroTitle: "நீங்கள் வளர்ப்பதன் மதிப்பை அதிகம் வைத்திருங்கள்.", heroText: "பயிர் பட்டியல், வாங்குபவர்கள், போக்குவரத்து, சேமிப்பு மற்றும் வெளிப்படையான தீர்வுக்கான பணியிடம்.", access: "DirectAgri அணுகல்", create: "கணக்கை உருவாக்கு", welcome: "மீண்டும் வரவேற்கிறோம்", chooseRole: "உங்கள் பணிக்கு பொருந்தும் பங்கைத் தேர்வு செய்யுங்கள்.", signInText: "உங்கள் DirectAgri கணக்கில் உள்நுழைக.", name: "முழுப் பெயர்", email: "மின்னஞ்சல்", password: "கடவுச்சொல்", role: "உங்கள் பங்கு", forgot: "கடவுச்சொல் மறந்துவிட்டதா?", submitCreate: "கணக்கை உருவாக்கு", submitLogin: "உள்நுழை", opening: "பணியிடம் திறக்கப்படுகிறது...", demo: "டெமோ உள்நுழைவு · கடவுச்சொல் demo1234", storage: "சேமிப்பு கூட்டாளர்" },
  gu: { already: "ખાતું છે? લોગ ઇન કરો", newHere: "નવા છો? સાઇન અપ કરો", eyebrow: "ખેતરથી બજાર સુધીનો યોગ્ય માર્ગ", heroTitle: "તમારા પાકનું વધુ મૂલ્ય રાખો.", heroText: "પાક યાદી, ખરીદદારો, પરિવહન, સંગ્રહ અને પારદર્શક ચુકવણી માટેનું કાર્યસ્થળ.", access: "DirectAgri પ્રવેશ", create: "ખાતું બનાવો", welcome: "ફરી સ્વાગત છે", chooseRole: "તમારા કામને અનુરૂપ ભૂમિકા પસંદ કરો.", signInText: "તમારા DirectAgri ખાતાથી લોગ ઇન કરો.", name: "પૂરું નામ", email: "ઇમેલ", password: "પાસવર્ડ", role: "તમારી ભૂમિકા", forgot: "પાસવર્ડ ભૂલી ગયા?", submitCreate: "ખાતું બનાવો", submitLogin: "લોગ ઇન", opening: "કાર્યસ્થળ ખુલી રહ્યું છે...", demo: "ડેમો લોગિન · પાસવર્ડ demo1234", storage: "સંગ્રહ ભાગીદાર" },
  ur: { already: "اکاؤنٹ ہے؟ لاگ ان کریں", newHere: "نئے ہیں؟ سائن اپ کریں", eyebrow: "کھیت سے بازار تک منصفانہ راستہ", heroTitle: "اپنی پیداوار کی زیادہ قدر رکھیں۔", heroText: "فصل کی فہرست، خریدار، نقل و حمل، ذخیرہ اور شفاف ادائیگی کا ایک ورک اسپیس۔", access: "DirectAgri رسائی", create: "اکاؤنٹ بنائیں", welcome: "واپسی پر خوش آمدید", chooseRole: "اپنے کام سے متعلق کردار منتخب کریں۔", signInText: "اپنے DirectAgri اکاؤنٹ سے لاگ ان کریں۔", name: "پورا نام", email: "ای میل", password: "پاس ورڈ", role: "آپ کا کردار", forgot: "پاس ورڈ بھول گئے؟", submitCreate: "اکاؤنٹ بنائیں", submitLogin: "لاگ ان", opening: "ورک اسپیس کھل رہا ہے...", demo: "ڈیمو لاگ ان · پاس ورڈ demo1234", storage: "ذخیرہ شراکت دار" },
  kn: { already: "ಖಾತೆ ಇದೆಯೇ? ಲಾಗ್ ಇನ್ ಮಾಡಿ", newHere: "ಹೊಸಬರೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ", eyebrow: "ಜಮೀನಿನಿಂದ ಮಾರುಕಟ್ಟೆಗೆ ನ್ಯಾಯಯುತ ದಾರಿ", heroTitle: "ನೀವು ಬೆಳೆದದ್ದರ ಹೆಚ್ಚಿನ ಮೌಲ್ಯವನ್ನು ಉಳಿಸಿಕೊಳ್ಳಿ.", heroText: "ಬೆಳೆ ಪಟ್ಟಿ, ಖರೀದಿದಾರರು, ಸಾರಿಗೆ, ಸಂಗ್ರಹ ಮತ್ತು ಪಾರದರ್ಶಕ ಪಾವತಿಗೆ ಒಂದು ಕಾರ್ಯಸ್ಥಳ.", access: "DirectAgri ಪ್ರವೇಶ", create: "ಖಾತೆ ರಚಿಸಿ", welcome: "ಮತ್ತೆ ಸ್ವಾಗತ", chooseRole: "ನಿಮ್ಮ ಕೆಲಸಕ್ಕೆ ಹೊಂದುವ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.", signInText: "ನಿಮ್ಮ DirectAgri ಖಾತೆಯಿಂದ ಲಾಗ್ ಇನ್ ಮಾಡಿ.", name: "ಪೂರ್ಣ ಹೆಸರು", email: "ಇಮೇಲ್", password: "ಪಾಸ್‌ವರ್ಡ್", role: "ನಿಮ್ಮ ಪಾತ್ರ", forgot: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?", submitCreate: "ಖಾತೆ ರಚಿಸಿ", submitLogin: "ಲಾಗ್ ಇನ್", opening: "ಕಾರ್ಯಸ್ಥಳ ತೆರೆಯುತ್ತಿದೆ...", demo: "ಡೆಮೋ ಲಾಗಿನ್ · ಪಾಸ್‌ವರ್ಡ್ demo1234", storage: "ಸಂಗ್ರಹ ಪಾಲುದಾರ" }
};

export const dashboardTranslations = {
  en: { farmer: "Farmer", buyer: "Buyer", transporter: "Transporter", storage: "Storage", government: "Government", console: "console", limited: "Your workspace is limited to this role.", rbac: "RBAC proof point", rbacText: "Storage can update location and quality records, while crop pricing remains farmer-owned.", demand: "Demand forecast", mocked: "Mocked e-NAM", mandi: "Mandi price", platform: "Platform average", farmerPanel: "Farmer", listing: "WhatsApp-style listing parser", saving: "Saving...", crop: "Crop", quantity: "Quantity", price: "Price", ownListings: "of your listings are in this inventory.", available: "Available stock", escrow: "Escrow value", quality: "Average quality", negotiate: "Negotiate batch", submit: "Submitting...", bulkOrder: "Create bulk order", release: "Release escrow", route: "Nearest-neighbor gig route", nearby: "Nearby pickup", accept: "Accept available delivery", delivery: "Delivery", storagePanel: "Quality record at check-in", photo: "Photo upload", photoText: "Demo mode records a quality score without external vision calls.", score: "Quality score", pending: "Pending check-ins", rent: "Rent ledger", governmentPanel: "Read-only impact dashboard", districts: "Districts covered", audited: "Batches audited", disputes: "Open disputes", audits: "Audit events", ministry: "Ministry view", ministryText: "This dashboard is read-only: policy teams can inspect adoption, price uplift, quality records, and audit events without affecting live trade.", inventoryTitle: "Farmer-owned crop batches", batch: "Batch", owner: "Owner", status: "Status", records: "records", onFarm: "On farm", inTransit: "In transit", stored: "Stored", sold: "Sold", kg: "kg", from: "from", checkedIn: "Checked in", checkedOut: "Checked out", successfully: "successfully.", offerSent: "Offer submitted", orderCreated: "Order created and escrow locked.", escrowReleased: "Escrow released and payment records created.", accepted: "accepted.", margin: "Farmer margin recovered", participants: "Verified participants", active: "Active crop batches", uplift: "Mandi benchmark uplift", error: "Something went wrong." },
  hi: { farmer: "किसान", buyer: "खरीदार", transporter: "परिवहनकर्ता", storage: "भंडारण", government: "सरकार", console: "कंसोल", limited: "आपका कार्यक्षेत्र इसी भूमिका तक सीमित है।", rbac: "RBAC प्रमाण", rbacText: "भंडारण स्थान और गुणवत्ता रिकॉर्ड बदल सकता है, लेकिन फसल का मूल्य किसान के पास रहता है।", demand: "मांग का अनुमान", mocked: "डेमो e-NAM", mandi: "मंडी भाव", platform: "प्लेटफॉर्म औसत", farmerPanel: "किसान", listing: "WhatsApp जैसा फसल सूचीकरण", saving: "सहेज रहे हैं...", crop: "फसल", quantity: "मात्रा", price: "भाव", ownListings: "सूची आपकी इन्वेंटरी में हैं।", available: "उपलब्ध स्टॉक", escrow: "एस्क्रो मूल्य", quality: "औसत गुणवत्ता", negotiate: "बैच पर बातचीत", submit: "भेज रहे हैं...", bulkOrder: "थोक ऑर्डर बनाएं", release: "एस्क्रो जारी करें", route: "निकटतम मार्ग योजना", nearby: "नजदीकी पिकअप", accept: "उपलब्ध डिलीवरी स्वीकार करें", delivery: "डिलीवरी", storagePanel: "चेक-इन पर गुणवत्ता रिकॉर्ड", photo: "फोटो अपलोड", photoText: "डेमो में बाहरी विज़न कॉल के बिना गुणवत्ता स्कोर दर्ज होता है।", score: "गुणवत्ता स्कोर", pending: "लंबित चेक-इन", rent: "किराया खाता", governmentPanel: "केवल-पठन प्रभाव डैशबोर्ड", districts: "कवर किए जिले", audited: "ऑडिट किए बैच", disputes: "खुले विवाद", audits: "ऑडिट घटनाएं", ministry: "मंत्रालय दृश्य", ministryText: "यह डैशबोर्ड केवल-पठन है: नीति टीमें व्यापार बदले बिना अपनाने, मूल्य वृद्धि, गुणवत्ता और ऑडिट देख सकती हैं।", inventoryTitle: "किसान के स्वामित्व वाले फसल बैच", batch: "बैच", owner: "मालिक", status: "स्थिति", records: "रिकॉर्ड", onFarm: "खेत पर", inTransit: "रास्ते में", stored: "भंडारित", sold: "बिक गया", kg: "किलो", from: "से", checkedIn: "चेक-इन", checkedOut: "चेक-आउट", successfully: "सफलतापूर्वक।", offerSent: "प्रस्ताव भेजा गया", orderCreated: "ऑर्डर बन गया और एस्क्रो लॉक है।", escrowReleased: "एस्क्रो जारी हुआ और भुगतान रिकॉर्ड बन गए।", accepted: "स्वीकार हुआ।", margin: "किसान का वापस मिला मार्जिन", participants: "सत्यापित प्रतिभागी", active: "सक्रिय फसल बैच", uplift: "मंडी भाव वृद्धि", error: "कुछ गलत हुआ।" }
};

for (const locale of Object.keys(authTranslations)) {
  authTranslations[locale] = { ...authTranslations.en, ...authTranslations[locale] };
}
for (const locale of Object.keys(dashboardTranslations)) {
  dashboardTranslations[locale] = { ...dashboardTranslations.en, ...dashboardTranslations[locale] };
}

for (const locale of ["mr", "bn", "te", "ta", "gu", "ur", "kn"]) {
  dashboardTranslations[locale] = { ...dashboardTranslations.en, ...(dashboardTranslations[locale] ?? {}) };
}
